# Generated by Django 5.2.3 on 2025-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('order_status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('cancel', 'Cancel')], max_length=20, null=True)),
                ('order_purchase_date', models.DateField(null=True)),
                ('order_amount', models.FloatField()),
                ('order_shipping', models.FloatField()),
                ('marketplace', models.CharField(choices=[('amazon', 'Amazon'), ('cdiscount', 'Cdiscount')], max_length=20)),
            ],
        ),
    ]
